* SRFI 117: Queues based on lists
  
** Original Implementation by John Cowan
*** Bigloo Port by Joseph Donaldson



keywords: [[https://srfi.schemers.org/?keywords=data-structure][Data Structure]], [[https://srfi.schemers.org/?keywords=r7rs-large][R7RS Large]], [[https://srfi.schemers.org/?keywords=r7rs-large-red][R7RS Large: Red Edition]]

This repository hosts [[https://srfi.schemers.org/srfi-117/][SRFI 117]]: Queues based on lists, a [[https://srfi.schemers.org/][Scheme Request for Implementation]].

This SRFI is in /final/ status.

The full documentation for this SRFI can be found in the [[https://srfi.schemers.org/srfi-117/srfi-117.html][SRFI Document]].

If you'd like to participate in the discussion of this SRFI, or report issues with it, please [[https://srfi.schemers.org/srfi-117/][join the SRFI-117 mailing list]] and send your message there.

Thank you.


[[mailto:srfi-editors@srfi.schemers.org][The SRFI Editors]]

** Building
Both the Bigloo native and jvm backends are supported. To build, execute 
   #+begin_src shell
  ./configure --prefix<installation path prefix>; make 
#+end_src 
where =<installation path prefix>= is the desired installation path
prefix (e.g, =/usr/local=). You usually want the path prefix to match
that used by Bigloo itself.

** Installation 
  To install the library, execute:
#+begin_src shell
  make install
#+end_src 

** Tests
To run the tests execute:

  #+begin_src shell
  make test
#+end_src
