* SRFI 117: Queues based on lists
  
** Original Implementation by John Cowan
*** Bigloo Port by Joseph Donaldson



keywords: [[https://srfi.schemers.org/?keywords=data-structure][Data Structure]], [[https://srfi.schemers.org/?keywords=r7rs-large][R7RS Large]], [[https://srfi.schemers.org/?keywords=r7rs-large-red][R7RS Large: Red Edition]]

This repository hosts [[https://srfi.schemers.org/srfi-117/][SRFI 117]]: Queues based on lists, a [[https://srfi.schemers.org/][Scheme Request for Implementation]].

This SRFI is in /final/ status.

The full documentation for this SRFI can be found in the [[https://srfi.schemers.org/srfi-117/srfi-117.html][SRFI Document]].

If you'd like to participate in the discussion of this SRFI, or report issues with it, please [[https://srfi.schemers.org/srfi-117/][join the SRFI-117 mailing list]] and send your message there.

Thank you.


[[mailto:srfi-editors@srfi.schemers.org][The SRFI Editors]]

** Building
    Both the Bigloo native and jvm backends are supported. To build the native library, execute
    
    ~make~
    
    To build the JVM library, execute

    ~make jvm~

    To build both, execute
 
    ~make all~

** Installation
   To install the library, execute 

   ~make install~

   This by default installs the library into /usr/lib/bigloo. If you have Bigloo installed to a different prefix, execute 
   
   ~make install DESTDIR=/path/prefix~

   This will result in the library being installed /path/prefix/lib/bigloo.

** Tests
   To run the tests, you will need to install [[https://github.com/donaldsonjw/btest][btest]]. Once this is done, the native tests can be executed with 
   
   ~make test~

   and the jvm tests can be executed with 

   ~make jtest~
